python3 run_bertcrf.py \
    --data_dir ./train/ \
    --model_type bertcrf \
    --model_name_or_path vinai/phobert-base \
    --output_dir ./model_output/ \
    --max_seq_length 128 \
    --per_gpu_train_batch_size 8 \
    --per_gpu_eval_batch_size 8 \
    --gradient_accumulation_steps 8 \
    --learning_rate 5e-5 \
    --num_train_epochs 10 \
    --save_steps 5000 \
    --logging_steps 200 \
    --seed 0 \
    --do_train \
    --do_eval \
    --evaluate_during_training \
    --overwrite_output_dir \